start_num: 0
config:
  experiment_data:
    entity: fslgroup
    project_name: rwkv
    experiment_tag: 'baseline'
    experiment_type: startnum_${start_num}
    experiment_name: baseline-nolrdecay-nolosswrap
    experiment_dir: null
    experiment_notes: 
    seed: 0
    gpu_id: 0
   
  model:
    name: rwkv
    kwargs:
      embedding_dim: 512
      attention_dim: 512
      ffn_dim: 2048
      num_blocks: 6
      vocab_size: 6064 # will be set by data
      context_len: 512
      wkv_config: # set to null to use plain torch
        T_max: 1024
        float_mode: '16'
        device: 'cuda:0'
  
  trainer:
    # training_setup: supervised-universal
    n_epochs: 10 #default: 500
    val_every: 5
    save_every: 24e3 
    batch_size: 12
    optimizer:
      name: Adam
      kwargs:
        lr: 0.0008
    # loss: crossentropy
    # metrics:
    # - MulticlassAccuracy:
    #     top_k: 1
    #     num_classes: 10
    num_workers: 4

  data:
    name: enwik8 
    kwargs: 
      batch_size: 12
      datafile: '/system/user/beck/pwbeck/projects/rwkv/RWKV-LM/data/enwik8'
      context_length: 512