start_num: 0
config:
  experiment_data:
    entity: fslgroup
    project_name: rwkv
    experiment_tag: '0.0'
    experiment_type: startnum_${start_num}
    experiment_name: hello_world
    experiment_dir: null
    experiment_notes: 
    seed: 0
    gpu_id: 1
   
  model:
    name: rwkv
    kwargs:
      embedding_dim: 512
      attention_dim: 512
      ffn_dim: 2048
      num_blocks: 6
      vocab_size: 0 # will be set by data
      context_len: 512
      wkv_config: # set to null to use plain torch
        T_max: 1024
        float_mode: 16
  
  trainer:
    training_setup: supervised-universal
    n_epochs: 50 #default: 500
    val_every: 5
    save_every: 24e3 
    batch_size: 12
    optimizer:
      name: AdamW
      kwargs:
        lr: 0.0008
        weight_decay: 0.0
    # loss: crossentropy
    # metrics:
    # - MulticlassAccuracy:
    #     top_k: 1
    #     num_classes: 10
    num_workers: 4

  data:
    # data config